name: CI and Deploy to Vercel

on:
  pull_request:
    branches: [dev, qas, main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build
    # Solo despliega en push (no en pull_request)
    if: github.event_name == 'push'

    # GitHub environment segun la branch
    environment: ${{ github.ref == 'refs/heads/main' && 'prd' || github.ref == 'refs/heads/qas' && 'qas' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            echo "Deploying PRODUCTION to Vercel from main..."
            vercel --prod --yes --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID"
          else
            echo "Deploying PREVIEW to Vercel from branch ${GITHUB_REF}..."
            vercel --yes --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID"
          fi